#!/bin/sh
dwm & dwm-bar
# relaunch DWM if the binary changes, otherwise bail
#while true ; do
#    dwm >/dev/null 2>&1 & dwm-bar
#done
#csum=""
#new_csum=$(sha1sum $(which dwm))
#while true
#do
#    if [ "$csum" != "$new_csum" ]
#    then
#        csum=$new_csum
#        dwm &
#        dwm-bar
#    else
#        exit 0
#    fi
#    new_csum=$(sha1sum $(which dwm))
#    sleep 0.5
#done
